import { Order, MOCK_ACCOUNT_ID } from "./types";

export const MOCK_ORDERS: Order[] = [
  {
    id: "ord-001",
    order_number: 1,
    account_id: MOCK_ACCOUNT_ID,
    created_at: "2026-06-01T10:00:00Z",
    delivery_date: "2026-06-05",
    production_status: "delivered",
    customer_name: "Ferretería López",
    customer_phone: "555-8823",
    product_type: "Talonario",
    description: "500 talonarios de parqueo numerados",
    quantity: 500,
    size: "½ carta",
    material: "Bond 75g",
    colors: "Negra",
    finishing: { numbered: { from: 1, to: 500 }, glued: true },
    operator_notes: "Revisar sangrado antes de cortar",
    price_total: 150,
    payment_status: "paid",
  },
  {
    id: "ord-002",
    order_number: 2,
    account_id: MOCK_ACCOUNT_ID,
    created_at: "2026-06-02T09:00:00Z",
    delivery_date: "2026-06-05",
    production_status: "ready",
    customer_name: "Consultorio Médico Soto",
    customer_phone: "555-1122",
    product_type: "Tarjeta de visita",
    description: "500 tarjetas de visita full color",
    quantity: 500,
    size: "9x5cm",
    material: "Couché 350g",
    colors: "Full color",
    finishing: {},
    price_total: 80,
    payment_status: "partial",
    payment_advance: 40,
  },
  {
    id: "ord-003",
    order_number: 3,
    account_id: MOCK_ACCOUNT_ID,
    created_at: "2026-06-03T11:00:00Z",
    delivery_date: "2026-06-07",
    production_status: "printing",
    customer_name: "Supermercado El Ahorro",
    description: "1000 volantes promoción fin de semana",
    quantity: 1000,
    size: "A5",
    material: "Bond 60g",
    colors: "2 tintas",
    finishing: {},
    price_total: 120,
    payment_status: "pending",
  },
  {
    id: "ord-004",
    order_number: 4,
    account_id: MOCK_ACCOUNT_ID,
    created_at: "2026-06-04T08:00:00Z",
    delivery_date: "2026-06-10",
    production_status: "design",
    customer_name: "Inmobiliaria Nova",
    description: "Afiche A3 para exhibición",
    quantity: 20,
    size: "A3",
    material: "Couché 200g",
    colors: "Full color",
    finishing: {},
    operator_notes: "El cliente envía el arte el 06/06",
    price_total: 200,
    payment_status: "partial",
    payment_advance: 100,
  },
  {
    id: "ord-005",
    order_number: 5,
    account_id: MOCK_ACCOUNT_ID,
    created_at: "2026-06-05T07:30:00Z",
    delivery_date: "2026-06-06",
    production_status: "received",
    customer_name: "Colegio San Marcos",
    customer_phone: "555-9900",
    product_type: "Membrete",
    description: "Membretes para comunicados escolares",
    quantity: 1000,
    size: "Carta",
    material: "Bond 90g",
    colors: "2 tintas (azul y negro)",
    finishing: {},
    price_total: 95,
    payment_status: "pending",
  },
  {
    id: "ord-006",
    order_number: 6,
    account_id: MOCK_ACCOUNT_ID,
    created_at: "2026-06-05T09:00:00Z",
    delivery_date: "2026-06-12",
    production_status: "plate",
    customer_name: "Restaurante La Brasa",
    description: "Menús plastificados",
    quantity: 50,
    size: "A4",
    material: "Couché 300g + plastificado mate",
    colors: "Full color",
    finishing: {},
    price_total: 350,
    payment_status: "paid",
  },
];
