import { Order, MOCK_ACCOUNT_ID } from "./types";

export const MOCK_ORDERS: Order[] = [
  {
    id: "ord-001",
    order_number: 8838,
    account_id: MOCK_ACCOUNT_ID,
    created_at: "2026-05-20T10:00:00Z",
    order_date: "2026-05-20",
    delivery_date: "2026-06-01",
    production_status: "delivered",
    customer_name: "Belinda Supanque",
    customer_phone: "69043783",
    product_type: "Talonario",
    description: "500 talonarios de parqueo numerados",
    quantity: 500,
    delivered_quantity: 500,
    order_type: "trabajo",
    size: "½ carta",
    material: "Bond 75g",
    colors: "Negra",
    finishing: { numbered: { from: 1, to: 500 }, glued: true },
    operator_notes: "Revisar sangrado antes de cortar",
    price_total: 1500,
    payment_status: "paid",
    payment_advance: 1500,
    items: [
      {
        id: "item-001-1",
        detail: "500 talonarios de parqueo numerados",
        quantity: 500,
        price_unit: 3,
        delivery_date: "2026-06-01",
      },
    ],
  },
  {
    id: "ord-002",
    order_number: 8839,
    account_id: MOCK_ACCOUNT_ID,
    created_at: "2026-05-22T09:00:00Z",
    order_date: "2026-05-22",
    delivery_date: "2026-06-03",
    production_status: "ready",
    customer_name: "Stellar Designs Co.",
    customer_email: "contact@stellar.com",
    product_type: "Tarjeta de visita",
    description: "500 tarjetas de visita full color",
    quantity: 500,
    delivered_quantity: 0,
    order_type: "trabajo",
    size: "9x5cm",
    material: "Couché 350g",
    colors: "Full color",
    finishing: {},
    price_total: 800,
    payment_status: "partial",
    payment_advance: 400,
    items: [
      {
        id: "item-002-1",
        detail: "500 tarjetas de visita full color",
        quantity: 500,
        price_unit: 1.6,
        delivery_date: "2026-06-03",
      },
    ],
  },
  {
    id: "ord-003",
    order_number: 8840,
    account_id: MOCK_ACCOUNT_ID,
    created_at: "2026-05-25T11:00:00Z",
    order_date: "2026-05-25",
    delivery_date: "2026-06-07",
    production_status: "printing",
    customer_name: "Green Valley Real Estate",
    customer_email: "m.jones@gv-re.com",
    product_type: "Volante",
    description: "1000 volantes promoción fin de semana",
    quantity: 1000,
    delivered_quantity: 0,
    order_type: "cotizacion",
    size: "A5",
    material: "Bond 60g",
    colors: "2 tintas",
    finishing: {},
    price_total: 1200,
    payment_status: "pending",
    items: [
      {
        id: "item-003-1",
        detail: "1000 volantes promoción fin de semana",
        quantity: 1000,
        price_unit: 1.2,
        delivery_date: "2026-06-07",
      },
    ],
  },
  {
    id: "ord-004",
    order_number: 8841,
    account_id: MOCK_ACCOUNT_ID,
    created_at: "2026-05-28T08:00:00Z",
    order_date: "2026-05-28",
    delivery_date: "2026-06-10",
    production_status: "design",
    customer_name: "Apex Tech Solutions",
    customer_email: "billing@apex.tech",
    product_type: "Afiche",
    description: "Afiche A3 para exhibición corporativa",
    quantity: 20,
    delivered_quantity: 0,
    order_type: "trabajo",
    size: "A3",
    material: "Couché 200g",
    colors: "Full color",
    finishing: {},
    operator_notes: "El cliente envía el arte el 06/06",
    price_total: 2000,
    payment_status: "partial",
    payment_advance: 1000,
    items: [
      {
        id: "item-004-1",
        detail: "Afiche A3 para exhibición corporativa",
        quantity: 20,
        price_unit: 100,
        delivery_date: "2026-06-10",
      },
    ],
  },
  {
    id: "ord-005",
    order_number: 8842,
    account_id: MOCK_ACCOUNT_ID,
    created_at: "2026-06-01T07:30:00Z",
    order_date: "2026-06-01",
    delivery_date: "2026-06-05",
    production_status: "received",
    customer_name: "Lumina Event Co.",
    customer_email: "events@lumina.io",
    product_type: "Membrete",
    description: "Membretes para comunicados de eventos",
    quantity: 1000,
    delivered_quantity: 0,
    order_type: "trabajo",
    size: "Carta",
    material: "Bond 90g",
    colors: "2 tintas (azul y negro)",
    finishing: {},
    price_total: 950,
    payment_status: "pending",
    items: [
      {
        id: "item-005-1",
        detail: "Membretes para comunicados de eventos",
        quantity: 1000,
        price_unit: 0.95,
        delivery_date: "2026-06-05",
      },
    ],
  },
  {
    id: "ord-006",
    order_number: 8843,
    account_id: MOCK_ACCOUNT_ID,
    created_at: "2026-06-02T09:00:00Z",
    order_date: "2026-06-02",
    delivery_date: "2026-06-15",
    production_status: "plate",
    customer_name: "Volantes Rápido",
    customer_phone: "69043783",
    product_type: "Volante",
    description: "Menús plastificados para restaurante",
    quantity: 50,
    delivered_quantity: 25,
    order_type: "trabajo",
    size: "A4",
    material: "Couché 300g + plastificado mate",
    colors: "Full color",
    finishing: {},
    price_total: 3500,
    payment_status: "paid",
    payment_advance: 3500,
    items: [
      {
        id: "item-006-1",
        detail: "Menús plastificados para restaurante",
        quantity: 50,
        price_unit: 70,
        delivery_date: "2026-06-15",
      },
    ],
  },
];
